version: '3.8'

services:

  danxils-api:
    build: .
    container_name: danxils-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=10.105.0.188:9092
      - JWT_SECRET=your-very-secret-key
      - JWT_EXPIRATION=86400000
    networks:
      - kafka-oms_network

networks:
  kafka-oms_network:
    external: true
