server:
  port: 8080

spring:
  application:
    name: DANXILS-API

  kafka:
    bootstrap-servers: 10.105.0.188:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    org.springframework: INFO
    com.example.danxils: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
